services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: meucampus_turmas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - turmas_pgdata:/var/lib/postgresql/data

volumes:
  turmas_pgdata:
